{
 "title": "Myapp Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "rate interval",
    "query": "2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "total production rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(produced_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total consumption rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(consumed_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "net message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(produced_messages_per_partition_total[$interval])) - sum(rate(consumed_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "net message rate per paritition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partition) (rate(produced_messages_per_partition_total[$interval])) - sum by (partition) (rate(consumed_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "production rate per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partition) (rate(produced_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consumption rate per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partition) (rate(consumed_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "production rate per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(produced_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consumption rate per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(consumed_messages_per_partition_total[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "consumer lag per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (partition) (lag_per_partition) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "total consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(lag_per_partition)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "poll size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "poll_size", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "delta consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(lag_per_partition) - min(lag_per_partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "average poll interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(poll_interval_sum[$interval]))/sum(rate(poll_interval_count[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "poll interval per pod by quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "poll_interval", "legendFormat": "{{pod}} - {{quantile}}" }
   ]
  },
  {
   "title": "average message latency per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (partition) (rate(message_latency_sum[$interval]))/sum by (partition) (rate(message_latency_count[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "message latency per partition - max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(partition) (message_latency{quantile=\"1.0\"})",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "rebalances counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(rebalances_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Delays Inserted Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "delay_counter_total", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}